### ISSUE TITLE
"Place order" not working and no validation message showing.

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/booking-and-rental-manager-for-woocommerce#1]
![Screenshot_124](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/62114a38-59e2-4090-af44-25f595883f57)

**Comment by arifulislamnayem** [comment]
Please share the live URL of the issue.

**Comment by arifulislamnayem** [comment]
Please share the live URL.

**Comment by rabiul0420** [comment]
It's Okay Thanks.
