### ISSUE TITLE
In inventory showing seat available but can't purchase. Please describe how inventory manage.

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/booking-and-rental-manager-for-woocommerce#10]
![Screenshot_137](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/244019af-730c-4405-9db2-9acc13de4133)
![Screenshot_136](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/b3b7cabe-7a3e-4e6a-bcd6-f21be632e975)

**Comment by arifulislamnayem** [comment]
Could you please upload it on the live server and share the live URL of this issue? So I can review it properly.

**Comment by arifulislamnayem** [comment]
fixed. Please check with latest version.

**Comment by rabiul0420** [comment]
In inventory available quantity showing 0. But I can book 2 resort. How it possible?

![Screenshot_4](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/5d3578ce-2967-43af-b979-204169d46cc3)
![Screenshot_5](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/66481695-916b-4efc-bd76-ac0d7e24343e)

**Comment by arifulislamnayem** [comment]
You booked for 7 july. So the item will be available 8 july

**Comment by rabiul0420** [comment]
It should be fixed by date wise.

**Comment by arifulislamnayem** [comment]
I will do a video meeting with you.

**Comment by arifulislamnayem** [comment]
How it works:
1. I booked for 14 and 15 July. (1st screenshot) https://snipboard.io/StywU9.jpg
2. Now see the inventory screenshot where you can see the item available is 0 for 14 and 15 July. (2nd screenshot) https://snipboard.io/EGHIKz.jpg https://snipboard.io/Gat1iL.jpg
4. You can see the item is available from 16 July in inventory. (3rd screenshot) https://snipboard.io/CeJATg.jpg
