### ISSUE TITLE
Plugin size is too large.

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/booking-and-rental-manager-for-woocommerce#11]
booking-and-rental-manager plugin size too large, more than 20mb. Whereas our other plugins size are less than 5mb.

Please solve it asap.

**Comment by arifulislamnayem** [comment]
Please download the latest version from github and please test again.

**Comment by rabiul0420** [comment]
Thanks. Try to reduce more.

**Comment by rabiul0420** [comment]
Thanks. Try to reduce more.
