### ISSUE TITLE
Please fix the bug.

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/booking-and-rental-manager-for-woocommerce#12]
Check availability not working.

https://bookingrrrr.s4-tastewp.com/rent/rent-resort/

![Screenshot_2](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/e8410925-6579-49c5-b567-31220332420b)

**Comment by arifulislamnayem** [comment]
Please share the  live URL

**Comment by arifulislamnayem** [comment]
Bug fixed.

**Comment by rabiul0420** [comment]
Thanks

**Comment by rabiul0420** [comment]
Thanks
