### ISSUE TITLE
Pricing problem in checkout.

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/booking-and-rental-manager-for-woocommerce#17]
https://booking.mage-people.com/checkout/

![Screenshot_16](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/f7873f05-1639-4e00-be6d-a25651c0c7f7)

**Comment by arifulislamnayem** [comment]
<img src="https://i.ibb.co/Jst3LpV/Screenshot-from-2023-07-27-12-19-07.png" alt="Screenshot-from-2023-07-27-12-19-07" border="0">
I found no pricing issue on the cart/checkout.

**Comment by rabiul0420** [comment]
Please check properly.
