### ISSUE TITLE
Columns should be fixed.

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/booking-and-rental-manager-for-woocommerce#2]
![Screenshot_125](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/a6c4c145-0418-405e-b4c1-e8d16f33babe)

**Comment by arifulislamnayem** [comment]
Fixed

**Comment by rabiul0420** [comment]
Still now showing problem!

<img width="959" alt="Screenshot_1" src="https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/380e5584-4eec-427e-9b7a-4701e4d313aa">

**Comment by arifulislamnayem** [comment]
It is fixed. Please recheck with the latest version.

**Comment by rabiul0420** [comment]
Alignment should be fixed.

![Screenshot_1](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/2fe4cb0d-17ba-44f0-a6f1-912dd5a45db5)

**Comment by arifulislamnayem** [comment]
fixed. please check now with the latest version.

**Comment by rabiul0420** [comment]
It's Okay thanks.
