### ISSUE TITLE
"Book Now" not working and no validation message showing.

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/booking-and-rental-manager-for-woocommerce#3]
![Screenshot_126](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/958ff9fc-000d-4091-865f-5d311d70c735)

**Comment by arifulislamnayem** [comment]
Please share the live URL of the issue.

**Comment by rabiul0420** [comment]
https://servicerrrrrrr.s3-tastewp.com/rent/rent-car-for-single-day/

**Comment by arifulislamnayem** [comment]
The above link is expired. Please share the new URL.

**Comment by rabiul0420** [comment]
It's Okay. Thanks.
