### ISSUE TITLE
Order list modification is needed with total info and filter.

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/booking-and-rental-manager-for-woocommerce#4]
![Screenshot_127](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/f9d6dc1b-c1b4-40ae-8294-c34e1f46226f)

**Comment by arifulislamnayem** [comment]
Okay, will implement it.

**Comment by arifulislamnayem** [comment]
This is not implemented yet. Working on it.
