### ISSUE TITLE
How it possible? Please describe it. if it's bug then fix it.

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/booking-and-rental-manager-for-woocommerce#5]
![Screenshot_128](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/140c59ea-f5ea-48fe-9069-9ffa75940c47)
![Screenshot_129](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/d6048a20-2a28-478b-87d4-6ab16345d4fb)

**Comment by arifulislamnayem** [comment]
Fixed

**Comment by rabiul0420** [comment]
The issue not yet solve.

<img width="959" alt="Screenshot_1" src="https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/4734ac57-79aa-4f1a-9ed1-07bba981ffcf">

**Comment by arifulislamnayem** [comment]
It was a bug. Now it is fixed. Please recheck with the latest version.

**Comment by rabiul0420** [comment]
Please fix the alignment.

![Screenshot_1](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/0a36f9f0-00f0-47bd-9c26-1b6feb431159)

**Comment by rabiul0420** [comment]
It's Okay now. thanks.
