### ISSUE TITLE
Time should be displayed with time slot label. 

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/booking-and-rental-manager-for-woocommerce#6]
![Screenshot_130](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/e643eed7-b901-4cb9-8330-fb58a5963211)

**Comment by arifulislamnayem** [comment]
Users can add the time with the slot label.

**Comment by arifulislamnayem** [comment]
Not necessary. User has freedom to set the custom label

**Comment by rabiul0420** [comment]
It's Okay. Thanks so much.
