### ISSUE TITLE
Before book price showing 300 and after book it's showing 200. 

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/booking-and-rental-manager-for-woocommerce#7]
![Screenshot_131](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/a82f6064-d8e4-4bfb-a940-95fb1bbd44df)
![Screenshot_132](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/0a0d5731-7d51-4ea6-81c7-c141154c2c7a)

**Comment by arifulislamnayem** [comment]
Fixed.

**Comment by arifulislamnayem** [comment]
fixed. please recheck with the latest version.

**Comment by rabiul0420** [comment]
Please check here 
https://bookingrrrr.s4-tastewp.com/rent/dress-rent/

**Comment by arifulislamnayem** [comment]
Bug Fixed. Please do recheck. @rabiul0420
