### ISSUE TITLE
Confused! How calculate the price?

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/booking-and-rental-manager-for-woocommerce#8]
![Screenshot_133](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/ba380cfd-1812-4d8a-baf6-117483d890aa)
![Screenshot_134](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/4b520f10-0f67-4384-a37d-f64d4c81abfc)

**Comment by arifulislamnayem** [comment]
**General Price:** It has only one price field for all days.
**Day-Wise Price:** It has options to set different prices for each day.

**Comment by arifulislamnayem** [comment]
Its not any issue.

**Comment by rabiul0420** [comment]
https://bookingrrrr.s4-tastewp.com/rent/dress-rent/

Hourly rate $1. According to the calculation 24$ for 24 hour. but its 20$. How calculate this ?

**Comment by arifulislamnayem** [comment]
Only daily rate will be applied for custom date. Hourly rate is not applicable for custom date.

**Comment by rabiul0420** [comment]
If so, that's fine.
