### ISSUE TITLE
Validation message should be highlight . it's  better  if the validation message is separated. 

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/booking-and-rental-manager-for-woocommerce#9]
![Screenshot_135](https://github.com/magepeopleteam/booking-and-rental-manager-for-woocommerce/assets/30313066/393df800-313f-4cdc-af78-686df61585d2)

**Comment by arifulislamnayem** [comment]
The notice design depends on WooCommerce plugin CSS and Activated CSS.

**Comment by arifulislamnayem** [comment]
This is the design from woocommerce. Sometimes, this design comes from the activated theme.

**Comment by rabiul0420** [comment]
If so, that's fine.
